---
name: Example1
on:
  push:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix:
        number: [0,1,2,3,4,5,6,7,8,9]
    name: Build
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Hello-${{ matrix.number }}
      run: |
        echo "Hello World from self hosted runner on ${{ matrix.number }}"